services:
  postgres:
    ports:
      - "5432:5432"

  backend:
    ports:
      - "8000:8000"

    volumes:
      - ../backend/app:/app/app
      - ../backend/alembic:/app/alembic
      - ../backend/alembic.ini:/app/alembic.ini:ro